ALTER TABLE candidates
ADD COLUMN IF NOT EXISTS needs_human_review BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'not_required',
ADD COLUMN IF NOT EXISTS review_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS escalation_source TEXT NOT NULL DEFAULT 'none';
