server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }

  location ^~ /api/ {
    # Dynamically inject the resolver depending on Local vs Kubernetes
    resolver __DNS_RESOLVER__ valid=10s ipv6=off;
    set $backend "__API_URL__";
    
    # When using variables in proxy_pass, we must manually strip the /api/ prefix
    rewrite ^/api/(.*)$ /$1 break;
    
    proxy_pass $backend;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}